apiVersion: v1 
kind: Pod 
metadata:
  name: cyclictest 
  annotations:
    cpu-load-balancing.crio.io: "disable"
    irq-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
spec:
  # Map to the correct performance class in the cluster (from PAO)
  # Identify class names with "oc get runtimeclass"
  runtimeClassName: performance-openshift-node-performance-profile
  restartPolicy: Never 
  containers:
  - name: cyclictest
    image: quay.io/container-perf-tools/cyclictest
    imagePullPolicy: Always
    # Request and Limits must be identical for the Pod to be assigned to the QoS Guarantee
    resources:
      requests:
        memory: "200Mi"
        cpu: "4"
      limits:
        memory: "200Mi"
        cpu: "4"
    env:
    - name: tool
      value: "cyclictest"
    - name: DURATION
      value: "1h"
    # cyclictest should run with an RT Priority of 95 when testing for RAN DU
    - name: rt_priority
      value: "95"
    - name: INTERVAL
      value: "1000"
    - name: delay
      value: "0"
    - name: TRACE_THRESHOLD
      value: ""
    - name: EXTRA_ARGS
      value: ""
    securityContext:
      # Required for access to /dev/cpu_dma_latency and /sys/kernel/debug on the host
      privileged: true
  nodeSelector:
    node-role.kubernetes.io/worker: ""
