apiVersion: v1 
kind: Pod 
metadata:
  name: oslat
  annotations:
    cpu-load-balancing.crio.io: "disable"
    irq-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
spec:
  # Map to the correct performance class in the cluster (from PAO)
  # Identify class names with "oc get runtimeclass"
  runtimeClassName: performance-openshift-node-performance-profile
  restartPolicy: Never
  containers:
  - name: oslat 
    image: quay.io/organization/container-perf-tools/oslat
    imagePullPolicy: Always 
    # Request and Limits must be identical for the Pod to be assigned to the QoS Guarantee
    resources:
      requests:
        memory: "200Mi"
        cpu: "4"
      limits:
        memory: "200Mi"
        cpu: "4"
    env:
    - name: GIT_URL
      value: "false"
    - name: tool
      value: "oslat"
    - name: PRIO 
      value: "1"
    - name: delay
      value: "0"
    - name: RUNTIME_SECONDS 
      value: "30"
    - name: TRACE_THRESHOLD
      value: ""
    - name: EXTRA_ARGS
      value: ""
    securityContext:
      # TRACE_THRESHOLD requires privileged=true
      #privileged: true
      capabilities:
        add:
          - SYS_NICE
          - IPC_LOCK
  nodeSelector:
    node-role.kubernetes.io/worker: ""
