apiVersion: v1 
kind: Pod 
metadata:
  name: sysjitter 
  annotations:
    # Disable CPU balance with CRIO (yes this is disabling it)
    cpu-load-balancing.crio.io: "true"
spec:
  # Map to the correct performance class in the cluster (from PAO)
  runtimeClassName: performance-custom-class
  restartPolicy: Never 
  containers:
  - name: container-perf-tools 
    image: quay.io/jianzzha/perf-tools
    imagePullPolicy: IfNotPresent
    env:
    - name: tool
      value: "sysjitter"
    - name: RUNTIME_SECONDS 
      value: "3600"
    - name: THRESHOLD_NS
      value: "200"
    - name: USE_TASKSET
      value: "n"
    - name: DISABLE_CPU_BALANCE
      value: "y"
      # DISABLE_CPU_BALANCE requires privileged=true
    - name: manual
      value: "n"
    #- name: ssh_address
    #  value: "192.168.222.1"
    #- name: ssh_user
    #  value: root
    #- name: ssh_password
    #  value: ${SSH_PASSWD}

    securityContext:
      privileged: true
      #capabilities:
      #  add:
      #    - SYS_NICE
      #    - IPC_LOCK
      #    - SYS_RAWIO
    resources:
      limits:
        cpu: 9
        memory: "8000Mi"
      requests:
        cpu: 9
        memory: "8000Mi"
  nodeSelector:
    node-role.kubernetes.io/worker-rt: ""

