apiVersion: v1
kind: Pod
metadata:
  name: stress-ng
  # Note: crio annotations are not required since this is not a low latency pod, and
  # on some kernels, the cpu-load-balancing.crio.io annotation will interfere with
  # stress-ng's ability to distribute threads to different CPUs.
spec:
  restartPolicy: Never
  containers:
  - name: stress-ng
    image: quay.io/container-perf-tools/stress-ng
    imagePullPolicy: Always
    # Request and Limits must be identical for the Pod to be assigned to the QoS Guarantee
    resources:
      requests:
        memory: "200Mi"
        cpu: "4"
      limits:
        memory: "200Mi"
        cpu: "4"
    env:
    - name: tool
      value: "stress-ng"
    - name: DURATION
      value: "1h"
    - name: CPU_METHOD
      value: "matrixprod"
    - name: CPU_LOAD
      value: "100"
    - name: EXTRA_ARGS
      value: ""
  nodeSelector:
    node-role.kubernetes.io/worker: ""
