apiVersion: v1 
kind: Pod 
metadata:
  name: hwlatdetect 
spec:
  restartPolicy: Never
  containers:
  - name: hwlatdetect 
    image: quay.io/container-perf-tools/hwlatdetect
    imagePullPolicy: Always 
    # Request and Limits are not required - hwlat detector is done in the kernel
    env:
    - name: tool
      value: "hwlatdetect"
    - name: RUNTIME_SECONDS 
      value: "30"
    - name: THRESHOLD
      value: "10"
    - name: EXTRA_ARGS
      value: ""
    securityContext:
      # Required for access to /dev/cpu_dma_latency and /sys/kernel/debug on the host
      privileged: true
  nodeSelector:
    node-role.kubernetes.io/worker: ""
